'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={user:null,profiles:[],pid:null,profile:null,setup:null,goals:{},apps:[],events:[],active:null,detail:'vacancy',versions:[],route:0};
const statuses={descubierta:'Guardada',preparada:'Preparada',postulada:'Postulada',incompatible:'Incompatible',pendiente_revision_duplicado:'Posible duplicado',intento_no_confirmado:'Sin confirmación',entrevista:'Entrevista',rechazada:'Rechazada',vencida:'Vencida',en_revision:'En revisión',cv_leido:'CV leído',contactado:'Contactado',evaluacion:'Evaluación',oferta:'Oferta',bloqueada:'Bloqueada'};
const badge=s=>`<span class="badge ${['postulada','oferta','entrevista'].includes(s)?'success':['pendiente_revision_duplicado','intento_no_confirmado','bloqueada'].includes(s)?'warning':['incompatible','rechazada','vencida'].includes(s)?'error':''}">${esc(statuses[s]||s)}</span>`;
const empty=(title,text,link='',label='')=>`<div class="empty"><span class="empty-symbol" aria-hidden="true">✧</span><h3>${esc(title)}</h3><p>${esc(text)}</p>${link?`<a class="button secondary" href="${esc(link)}">${esc(label)}</a>`:''}</div>`;
function notice(text,error=false){const n=$('#notice');n.textContent=text;n.className=error?'error':'';n.hidden=false;}
async function api(path,method='GET',data){const options={method};if(data instanceof FormData)options.body=data;else if(data!==undefined){options.headers={'Content-Type':'application/json'};options.body=JSON.stringify(data);}const response=await fetch(path,options);if(response.status===401&&!path.startsWith('/api/auth/')){showAuth('login');throw Error('Tu sesión terminó. Vuelve a iniciar sesión.');}let value;try{value=await response.json();}catch{throw Error('El servidor no devolvió una respuesta válida. Revisa la conexión.');}if(!response.ok){let detail=value.detail;throw Error(typeof detail==='string'?detail:Array.isArray(detail)?detail.map(d=>d.msg).join(' · '):detail?.message||'No se pudo completar la operación.');}return value;}
function busy(button,fn){return async event=>{event?.preventDefault();if(button?.disabled)return;const original=button?.textContent;if(button){button.disabled=true;button.textContent='Un momento…';}try{await fn(event);}catch(e){notice(e.message,true);}finally{if(button){button.disabled=false;if(button.textContent==='Un momento…')button.textContent=original;}}};}
function bindForm(id,fn){const form=$(id);form.addEventListener('submit',busy(form.querySelector('button:not([type=button])'),fn));}
function theme(value){document.documentElement.dataset.theme=value||'light';}
const autoPortals={bumeran:'Bumeran',computrabajo:'Computrabajo',linkedin:'LinkedIn'};
const portalOf=url=>{try{const h=new URL(url).hostname;return Object.keys(autoPortals).find(k=>h.includes(k))||'';}catch{return '';}};
const runLabels={en_cola:'En cola',ejecutando:'Postulando ahora…',postulada:'Postulación confirmada',bloqueada:'Necesita tu intervención',intento_no_confirmado:'Sin confirmación del portal',error:'No se completó (no se envió)'};
const actionLabels={registrada:'Oportunidad guardada',auto_postulacion_autorizada:'Postulación automática autorizada',auto_postulacion_iniciada:'JobFlow abrió el portal',postulada:'Postulación confirmada',bloqueada:'Detenida: necesita tu intervención',intento_no_confirmado:'Intento sin confirmación',auto_postulacion_error:'Error técnico antes de enviar',cv_adaptado:'CV adaptado',cv_aprobado:'CV aprobado',preparada:'Respuestas preparadas',respuestas_aprobadas:'Respuestas aprobadas',preguntas_pendientes:'Postulada: quedan preguntas por responder',preguntas_respondidas:'Respuestas enviadas al portal'};
function confirmDialog(title,html,ok='Autorizar',destructive=false){return new Promise(resolve=>{const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-body').innerHTML=html;$('#confirm-ok').textContent=ok;$('#confirm-ok').classList.toggle('destructive',destructive);d.returnValue='';d.onclose=()=>resolve(d.returnValue==='ok');d.showModal();});}
function sentData(){const p=state.profile||{};return `<p>JobFlow solo usará tu perfil confirmado y las respuestas que aprobaste:</p><ul>${[['Pretensión salarial',p.rango_salarial],['Disponibilidad',p.disponibilidad],['Movilidad',p.movilidad],['Correo',p.email],['Teléfono',p.telefono]].filter(([,v])=>v).map(([k,v])=>`<li>${k}: ${esc(v)}</li>`).join('')}</ul><p class="muted-note">Si aparece una pregunta sin dato confirmado, un CAPTCHA, una prueba o una casilla de términos, se detiene y te avisa. Solo marca “postulada” cuando el portal lo confirma.</p>`;}
function href(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?esc(u.href):'';}catch{return '';}}
function dateLabel(value){if(!value)return '';const raw=/Z$|[+-]\d\d:\d\d$/.test(value)?value:value+'Z';return new Date(raw).toLocaleString('es-PE',{timeZone:state.setup?.settings.timezone||'America/Lima',dateStyle:'medium',timeStyle:'short'});}
function input(label,name,value='',type='text',full=false){return `<label class="${full?'full':''}">${esc(label)}<input type="${type}" name="${name}" value="${esc(value)}"></label>`;}
const salaryRanges=['Hasta S/1,500','S/1,500 – S/2,000','S/2,000 – S/2,500','S/2,500 – S/3,000','S/3,000 – S/3,500','S/3,500 – S/4,000','S/4,000 – S/5,000','S/5,000 – S/6,000','S/6,000 – S/8,000','Más de S/8,000'];
const restrictionOptions=['Sin turnos nocturnos','Sin horarios rotativos','Sin trabajo los fines de semana','Solo en planilla (con beneficios de ley)','Sueldo fijo (no solo comisiones)','Sin ventas de campo','Sin viajes frecuentes','Solo medio tiempo'];
const availabilityOptions=['Inmediata','En 1 semana','En 2 semanas','En 1 mes','En más de 1 mes'];
// Options start with «Sí,»/«No» so autofill can answer yes/no portal questions.
const mobilityOptions=['Sí, cuento con movilidad propia','Sí, cuento con movilidad propia y licencia de conducir','No, me movilizo en transporte público','No cuento con movilidad propia'];
function choiceOptions(value,options){const current=value&&!options.includes(value)?[`<option value="${esc(value)}" selected>${esc(value)} (valor actual)</option>`]:[];return `<option value="">Sin indicar</option>${current.join('')}${options.map(o=>`<option value="${esc(o)}"${o===value?' selected':''}>${esc(o)}</option>`).join('')}`;}
function choice(label,name,value,options,full=false){return `<label class="${full?'full':''}">${esc(label)}<select name="${name}">${choiceOptions(value,options)}</select></label>`;}
function area(label,name,value='',full=true){return `<label class="${full?'full':''}">${esc(label)}<textarea name="${name}" rows="3">${esc(value)}</textarea></label>`;}
function formObject(form){return Object.fromEntries(new FormData(form));}
function cpath(s){return `/api/career/profiles/${state.pid}/${s}`;}
async function refresh(){if(!state.pid)return;const pid=state.pid;const results=await Promise.all([api(`/api/profiles/${pid}`),api(`/api/career/profiles/${pid}/setup`),api(`/api/career/profiles/${pid}/goals`),api(`/api/applications?profile_id=${pid}`),api(`/api/career/profiles/${pid}/events`)]);if(pid!==state.pid)return;[state.profile,state.setup,state.goals,state.apps,state.events]=results;theme(state.setup.settings.theme);$('#export-tracker').href=`/api/tracker/export?profile_id=${pid}`;}
async function profiles(){const list=await api('/api/profiles');state.profiles=list;await claimPanel();$('#profile-picker').innerHTML=list.map(p=>`<option value="${p.id}">${esc(p.nombre||'Perfil sin nombre')}</option>`).join('');$('#profile-picker').closest('label').hidden=!list.length;if(!list.some(p=>p.id===state.pid))state.pid=list[0]?.id??null;renderProfiles();if(!list.length){state.profile=null;$('#profile-fields').innerHTML='';$('#experience-fields').innerHTML='';notice($('#claim-panel').hidden?'Carga tu primer CV para comenzar.':'Carga tu CV o pasa a tu cuenta un perfil que ya tenías.');return;}$('#profile-picker').value=state.pid;}
async function route(){const token=++state.route;const route=(location.hash.slice(1)||'today').split('/');const page=route[0]==='application'?'detail':route[0]==='portals'?'profile':route[0];if(!['today','profile','jobs','applications','detail','agenda','connections'].includes(page)){location.hash='today';return;}$$('[data-view]').forEach(el=>el.hidden=el.dataset.view!==page);$$('[data-page]').forEach(el=>{el.classList.toggle('active',el.dataset.page===(page==='detail'?'applications':page));if(el.classList.contains('active'))el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});if(!state.pid){if(state.user&&page!=='profile')location.hash='profile';return;}try{await refresh();if(token!==state.route)return;switch(page){case 'today':await today();break;case 'profile':renderProfile();if(route[0]==='portals')$('#portals-panel').scrollIntoView({behavior:'smooth'});break;case 'jobs':await jobs();break;case 'applications':renderApplications();break;case 'agenda':renderAgenda();break;case 'connections':await connections();break;case 'detail':state.active=Number(route[1]);state.detail='vacancy';await detail();break;}}catch(e){notice(e.message,true);}}
async function today(){const s=await api(cpath('summary'));const first=(state.profile.nombre||'').split(' ')[0];const hour=Number(new Intl.DateTimeFormat('es',{hour:'numeric',hourCycle:'h23',timeZone:state.setup.settings.timezone}).format(new Date()));$('#greeting').textContent=`${hour>=18?'Buenas noches':hour>=12?'Buenas tardes':'Buenos días'}${first?', '+first:''}.`;
$('#today-date').textContent=new Date().toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long',timeZone:state.setup.settings.timezone}).toUpperCase();$('#today-subtitle').textContent=s.counts.pending?`Tienes ${s.counts.pending} candidatura(s) que necesitan tu revisión.`:'Un espacio para avanzar con claridad, a tu ritmo.';
const ready=state.setup.confirmed&&state.setup.goals_confirmed;$('#onboarding').hidden=ready;$('#onboarding').innerHTML=`<div><strong>${state.setup.confirmed?'Elige tus puestos objetivo':'Tu perfil es el punto de partida'}</strong><p>${state.setup.confirmed?'Guarda tus preferencias antes de buscar oportunidades.':'Confirma tu experiencia para preparar postulaciones fieles a ti.'}</p></div><a class="button primary" href="#profile">${state.setup.confirmed?'Elegir mis objetivos':'Revisar mi perfil'}</a>`;
$('#today-stats').innerHTML=[['Confirmadas hoy',s.counts.confirmed,'Con evidencia registrada'],['Preparadas hoy',s.counts.prepared,'Listas para revisar'],['Necesitan atención',s.counts.pending,'Pendientes acumulados']].map(([title,n,note])=>`<a class="stat" href="#applications"><span>${title}</span><strong>${n}</strong><p>${note}</p></a>`).join('');
const rows=items=>items.map(i=>`<div class="activity-row"><div><a href="#application/${i.id}"><strong>${esc(i.title)}</strong></a><p>${esc(i.company)}</p></div>${badge(i.status)}</div>`).join('');
$('#today-pending').innerHTML=rows(s.pending.slice(0,5))||empty('Todo en orden por aquí','Cuando una candidatura necesite tu aprobación, la encontrarás en este espacio.');$('#today-activity').innerHTML=rows(s.activity)||empty('Hoy puedes dar el siguiente paso','Guarda una oportunidad para empezar a preparar tu candidatura.','#jobs','Buscar oportunidades');$('#today-agenda').innerHTML=s.upcoming.map(e=>`<div class="activity-row"><div><strong>${esc(e.title)}</strong><p>${esc(dateLabel(e.start))}</p><small>${e.confirmed?'Fecha confirmada':'Por confirmar'}</small></div></div>`).join('')||empty('Tu próximo encuentro','Las entrevistas y recordatorios aparecerán aquí.');}
const MONTHS=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Set','Oct','Nov','Dic'];
const plain=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').trim().toLowerCase();
const isPresent=s=>['actualidad','presente','actual','hoy'].includes(plain(s));
// Experience dates are stored as display text («Jun. 2025», «Actualidad»); keys are «2025-06» for comparisons.
function monthKey(s){const t=plain(s);if(/^\d{4}-(0[1-9]|1[0-2])$/.test(t))return t;const m=t.match(/^([a-z]{3})[a-z]*\.?\s+(\d{4})$/),i=m?MONTHS.map(plain).indexOf(m[1]==='sep'?'set':m[1]):-1;return i>=0?`${m[2]}-${String(i+1).padStart(2,'0')}`:'';}
const monthText=k=>`${MONTHS[Number(k.slice(5))-1]}. ${k.slice(0,4)}`;
function currentMonthKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function monthField(label,name,value=''){const key=monthKey(value),present=name==='fin'&&isPresent(value),legacy=Boolean(value)&&!key&&!present;return `<label>${esc(label)}<button type="button" class="month-field${legacy?' legacy':''}" data-month-field="${name}" aria-haspopup="dialog" aria-expanded="false">${esc(present?'Hasta la actualidad':key?monthText(key):legacy?`${value} · elige mes y año`:'Elegir mes y año')}</button><input type="hidden" name="${name}" value="${esc(present?'Actualidad':key?monthText(key):value)}"></label>`;}
function experienceField(e={},i=0){return `<fieldset class="experience"><legend>Experiencia ${i+1}</legend><div class="form-grid">${input('Empresa','empresa',e.empresa)}${input('Cargo formal, si consta','cargo',e.cargo)}${monthField('Inicio','inicio',e.inicio)}${monthField('Fin','fin',e.fin)}${area('Funciones, una por línea','bullets',(e.bullets||[]).join('\n'))}</div><button type="button" class="text-button" data-remove-experience>Quitar esta experiencia</button></fieldset>`;}
function renderProfile(){const p=state.profile;renderProfiles();portalsView().catch(e=>notice(e.message,true));$('#upload-title').textContent='Actualiza tu CV';$('#upload-text').textContent=`PDF, DOCX o TXT · hasta 10 MB. Reemplaza los datos de este perfil${p.fuente_cv?' (CV actual: '+p.fuente_cv+')':''}; no se crea otro.`;$('#profile-status').textContent=state.setup.confirmed?'Confirmado por ti':'Por revisar';$('#confirm-check').checked=false;
$('#confirm-profile').disabled=false;$('#profile-fields').innerHTML=input('Nombre completo','nombre',p.nombre)+input('Correo','email',p.email,'email')+input('Teléfono','telefono',p.telefono)+input('Ubicación','ubicacion',p.ubicacion)+input('Titular profesional','headline',p.headline)+input('LinkedIn','linkedin',p.linkedin,'url')+choice('Disponibilidad','disponibilidad',p.disponibilidad,availabilityOptions)+choice('Movilidad','movilidad',p.movilidad,mobilityOptions)+choice('Pretensión salarial confirmada (mensual)','rango_salarial',p.rango_salarial,salaryRanges)+area('Resumen profesional','summary',p.summary)+area('Formación, una por línea','educacion',(p.educacion||[]).join('\n'))+area('Herramientas: nombre | nivel, una por línea','skill_levels',(p.skills||[]).map(s=>s.join(' | ')).join('\n'))+area('Idiomas: idioma | nivel, uno por línea','languages',Object.entries(p.languages||{}).map(s=>s.join(' | ')).join('\n'))+area('Proyectos, uno por línea','proyectos',(p.proyectos||[]).join('\n'))+area('Datos pendientes que no deben afirmarse','pendientes',(p.pendientes||[]).join('\n'));
$('#experience-fields').innerHTML=(p.experiencia||[]).map(experienceField).join('');const g=state.goals,f=$('#goals-form');f.elements.salary.innerHTML=choiceOptions(g.salary,salaryRanges);for(const k of ['location','modality','seniority','salary'])if(g[k])f.elements[k].value=g[k];const chosen=String(g.restrictions||'').split(';').map(s=>s.trim()).filter(Boolean);$('#restriction-options').innerHTML=restrictionOptions.map(o=>`<label class="check"><input type="checkbox" value="${esc(o)}"${chosen.includes(o)?' checked':''}>${esc(o)}</label>`).join('');f.elements.restrictions_other.value=chosen.filter(s=>!restrictionOptions.includes(s)).join('\n');f.elements.titles.value=(g.titles||[]).join('\n');if(!g.location)f.elements.location.value=p.ubicacion||'';$('#goals-panel').querySelector('button').disabled=!state.setup.confirmed;}
const picker={field:null,year:0};
function relatedMonth(field,name){const h=field.closest('.experience')?.querySelector(`input[name=${name}]`);return h?monthKey(h.value):'';}
function drawMonthPicker(){const field=picker.field,end=field.dataset.monthField==='fin',selected=monthKey(field.nextElementSibling.value),now=currentMonthKey(),min=end?relatedMonth(field,'inicio'):'',other=end?'':relatedMonth(field,'fin'),max=other&&other<now?other:now,y=picker.year;
$('#month-picker').innerHTML=`<div class="month-head"><button type="button" data-year="-1" aria-label="Año anterior"${y<=1950?' disabled':''}>‹</button><strong aria-live="polite">${y}</strong><button type="button" data-year="1" aria-label="Año siguiente"${y>=Number(now.slice(0,4))?' disabled':''}>›</button></div><div class="month-grid">${MONTHS.map((m,i)=>{const k=`${y}-${String(i+1).padStart(2,'0')}`;return `<button type="button" data-month="${k}" aria-label="${m}. ${y}" class="${k===selected?'selected':''}"${k>max||(min&&k<min)?' disabled':''}>${m}</button>`;}).join('')}</div><div class="month-foot">${end?'<button type="button" class="button primary" data-present>Hasta la actualidad</button>':''}<button type="button" class="text-button" data-clear-month>Borrar fecha</button></div>`;}
function openMonthPicker(field){closeMonthPicker();const end=field.dataset.monthField==='fin',key=monthKey(field.nextElementSibling.value)||relatedMonth(field,end?'inicio':'fin')||currentMonthKey(),box=$('#month-picker');picker.field=field;picker.year=Number(key.slice(0,4));drawMonthPicker();box.setAttribute('aria-label',end?'Elegir mes y año de fin':'Elegir mes y año de inicio');box.hidden=false;const r=field.getBoundingClientRect(),w=box.offsetWidth,h=box.offsetHeight;box.style.left=Math.max(12,Math.min(r.left,innerWidth-w-12))+'px';box.style.top=(r.bottom+h+8>innerHeight&&r.top>h+8?r.top-h-6:Math.min(r.bottom+6,innerHeight-h-8))+'px';field.setAttribute('aria-expanded','true');(box.querySelector('.selected:not(:disabled)')||box.querySelector('[data-month]:not(:disabled)')||box.querySelector('.month-foot button'))?.focus({preventScroll:true});}
function closeMonthPicker(focus=false){const box=$('#month-picker'),field=picker.field;if(!field)return;box.hidden=true;field.setAttribute('aria-expanded','false');picker.field=null;if(focus)field.focus({preventScroll:true});}
function setMonth(stored){const field=picker.field;field.nextElementSibling.value=stored;field.textContent=stored==='Actualidad'?'Hasta la actualidad':stored||'Elegir mes y año';field.classList.remove('legacy');$('#confirm-profile').disabled=true;closeMonthPicker(true);}
$('#month-picker').onclick=e=>{e.stopPropagation();const b=e.target.closest('button');if(!b||b.disabled||!picker.field)return;if(b.dataset.year){picker.year+=Number(b.dataset.year);drawMonthPicker();($(`#month-picker [data-year="${b.dataset.year}"]:not(:disabled)`)||$('#month-picker [data-month]:not(:disabled)'))?.focus({preventScroll:true});}else if(b.dataset.month)setMonth(monthText(b.dataset.month));else if(b.hasAttribute('data-present'))setMonth('Actualidad');else if(b.hasAttribute('data-clear-month'))setMonth('');};
document.addEventListener('click',e=>{if(picker.field&&!e.target.closest('#month-picker,[data-month-field]'))closeMonthPicker();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&picker.field)closeMonthPicker(true);});window.addEventListener('resize',()=>closeMonthPicker());window.addEventListener('scroll',()=>closeMonthPicker(),true);
const lines=s=>String(s||'').split('\n').map(s=>s.trim()).filter(Boolean);
bindForm('#upload-form',async event=>{const data=new FormData($('#upload-form')),mode=state.pid?event.submitter?.dataset.upload||'update':'new';if(mode==='new'&&state.profiles.length>=state.user.max_profiles)throw Error(`Puedes tener hasta ${state.user.max_profiles} perfiles. Borra alguno para crear otro.`);if(mode==='update'){if(!await confirmDialog('¿Actualizar este perfil con el nuevo CV?',`<p>Los datos de <strong>${esc(state.profile?.nombre||'este perfil')}</strong> se reemplazarán por los del CV adjunto. No se creará otro perfil.</p><p class="muted-note">Tus correcciones manuales se sobrescriben y tendrás que revisar y confirmar los datos otra vez. Tus postulaciones y objetivos se conservan.</p>`,'Actualizar perfil'))return;data.append('profile_id',state.pid);}const result=await api('/api/cv/upload','POST',data);state.pid=result.id;$('#upload-form').reset();await profiles();await refresh();renderProfile();notice(result.actualizado?'Perfil actualizado con el nuevo CV. Revisa los datos y confírmalos otra vez.':'CV extraído. Revisa y corrige sus datos antes de confirmar.');});
bindForm('#profile-form',async()=>{const f=$('#profile-form'),data=formObject(f);for(const k of ['empresa','cargo','inicio','fin','bullets'])delete data[k];for(const k of ['educacion','proyectos','pendientes'])data[k]=lines(data[k]);const pairs=s=>lines(s).map(line=>{const [a,...rest]=line.split('|');return [a.trim(),rest.join('|').trim()];});data.skill_levels=pairs(data.skill_levels);data.languages=Object.fromEntries(pairs(data.languages));data.experiencia=$$('.experience').map((el,i)=>{const v={};el.querySelectorAll('input[name],textarea[name]').forEach(x=>v[x.name]=x.value.trim());v.bullets=lines(v.bullets);const a=monthKey(v.inicio),b=monthKey(v.fin);if(a&&b&&b<a)throw Error(`En la experiencia ${i+1}, el fin no puede ser anterior al inicio.`);return v;});await api(`/api/profiles/${state.pid}`,'PATCH',data);await refresh();renderProfile();notice('Correcciones guardadas. Confirma los datos actualizados.');});
$('#profile-form').addEventListener('input',()=>{$('#confirm-profile').disabled=true;$('#confirm-check').checked=false;});
$('#add-experience').onclick=()=>{$('#experience-fields').insertAdjacentHTML('beforeend',experienceField({},$$('.experience').length));$('#confirm-profile').disabled=true;};$('#experience-fields').onclick=e=>{const field=e.target.closest('[data-month-field]');if(field){e.preventDefault();if(picker.field===field)closeMonthPicker();else openMonthPicker(field);return;}if(e.target.hasAttribute('data-remove-experience')){e.target.closest('fieldset').remove();$('#confirm-profile').disabled=true;}};
$('#confirm-profile').onclick=busy($('#confirm-profile'),async()=>{if(!$('#confirm-check').checked)throw Error('Marca la confirmación después de revisar los datos guardados.');await api(cpath('confirm'),'POST',{accepted:true,profile_hash:state.setup.profile_hash});await refresh();renderProfile();$('#goals-panel').scrollIntoView({behavior:'smooth'});notice('Perfil confirmado. Ahora elige tus puestos objetivo.');});
bindForm('#goals-form',async()=>{const data=formObject($('#goals-form'));data.titles=lines(data.titles);data.restrictions=[...$$('#restriction-options input:checked').map(i=>i.value),...String(data.restrictions_other||'').split(/[;\n]/).map(s=>s.trim()).filter(Boolean)].join('; ');delete data.restrictions_other;await api(cpath('goals'),'PUT',data);notice('Objetivos guardados. La búsqueda utilizará estos puestos.');location.hash='jobs';});
async function jobs(){$('#import-form button[type=submit], #import-form button:not([type])').disabled=!(state.setup.confirmed&&state.setup.goals_confirmed);const targets=await api(`/api/profiles/${state.pid}/puestos`);$('#search-target').innerHTML=targets.map(t=>`<option value="${t.id}">${esc(t.titulo)}</option>`).join('');const ready=state.setup.confirmed&&state.setup.goals_confirmed;$('#search-form button').disabled=!ready;$('#search-preferences').textContent=ready?`${state.goals.location} · ${state.goals.modality} · ${state.goals.salary||'Salario por evaluar'}${state.goals.restrictions?' · Revisar: '+state.goals.restrictions:' · Sin restricciones'}`:'Primero confirma tu CV y guarda los puestos deseados en Mi perfil.';}
$('#toggle-import').onclick=()=>{$('#import-panel').hidden=!$('#import-panel').hidden;};
bindForm('#search-form',async()=>{const pid=state.pid;$('#search-status').textContent='Buscando ofertas. Algunas plataformas pueden pedir que abras su sitio.';const r=await api('/api/jobs/search','POST',{profile_id:pid,target_id:Number($('#search-target').value)});if(pid!==state.pid)return;const total=r.plataformas.reduce((n,p)=>n+(p.resultados||[]).length,0);$('#search-status').textContent=`Búsqueda terminada: ${total} vacantes compatibles. Guarda las que te interesen para leer el aviso completo.`;$('#job-results').innerHTML=r.plataformas.map(p=>`<article class="panel"><div class="section-heading"><h2>${esc(p.nombre||p.plataforma)}${autoPortals[p.plataforma]?' <span class="badge success">Postulación automática</span>':''}</h2><a target="_blank" rel="noopener noreferrer" href="${href(p.url)}">Abrir búsqueda original ↗</a></div><p>${esc(p.nota||'Resultados encontrados')}</p><div class="job-grid">${(p.resultados||[]).map(j=>`<div class="job-card"><p class="company">${esc(j.empresa||'Empresa no indicada')}</p><h3>${esc(j.titulo)}</h3><p class="job-meta">${esc([j.ubicacion,j.modalidad,j.fecha_publicacion?'Publicada el '+j.fecha_publicacion:''].filter(Boolean).join(' · '))}</p><div class="match"><strong>${esc(j.match)}/100 · Compatibilidad estimada</strong>${j.descripcion?`<br>${esc(j.descripcion.slice(0,170))}…`:''}</div><div class="actions"><a class="button secondary" href="${href(j.link)}" target="_blank" rel="noopener noreferrer">Ver anuncio ↗</a><button class="button primary" data-import-job="${esc(JSON.stringify({titulo:j.titulo,empresa:j.empresa,ubicacion:j.ubicacion,modalidad:j.modalidad,fecha_publicacion:j.fecha_publicacion,url:j.link,plataforma:p.plataforma}))}">Guardar y evaluar</button></div></div>`).join('')||empty('Revisa el portal original',p.estado==='requiere_navegador'?'Este portal no permite la lectura automática. Abre la búsqueda y pega aquí el enlace del aviso.':'Prueba con otro puesto objetivo o revisa el portal.')}</div></article>`).join('');});
const importKeys=['titulo','empresa','plataforma','url','descripcion','ubicacion','modalidad','vigente','anos_obligatorios','herramientas','formacion','salario_max','fecha_publicacion'];
async function saveJob(job){const data={profile_id:state.pid};for(const k of importKeys)if(job[k]!==undefined&&job[k]!==null&&job[k]!=='')data[k]=job[k];data.empresa=data.empresa&&data.empresa.length>1?data.empresa:'Empresa no indicada';data.descripcion=String(data.descripcion||'').slice(0,40000);return api('/api/jobs/import','POST',data);}
function fillImport(j){$('#import-panel').hidden=false;const f=$('#import-form');f.reset();for(const k of ['titulo','empresa','ubicacion','modalidad','descripcion','formacion','anos_obligatorios','salario_max','fecha_publicacion','url'])if(f.elements[k]&&j[k]!=null)f.elements[k].value=j[k];if([...f.elements.plataforma.options].some(o=>o.value===j.plataforma))f.elements.plataforma.value=j.plataforma;f.elements.herramientas.value=(j.herramientas||[]).join(', ');f.elements.vigente.value=j.vigente===false?'false':'';if(j.anos_obligatorios!=null||j.herramientas?.length)f.querySelector('details').open=true;}
const fieldNames={empresa:'empresa',ubicacion:'ubicación',modalidad:'modalidad',fecha_publicacion:'fecha',salario_max:'salario',herramientas:'herramientas'};
bindForm('#extract-form',async()=>{$('#extract-status').textContent='Leyendo el aviso…';try{const j=await api('/api/jobs/extract','POST',{url:$('#extract-form').elements.url.value});fillImport(j);$('#extract-status').textContent=`Datos leídos del anuncio de ${j.plataforma==='manual'?'la empresa':j.plataforma}.${j.campos_vacios.length?' No publica: '+j.campos_vacios.map(k=>fieldNames[k]||k).join(', ')+'.':''} Revisa y guarda.`;}catch(e){$('#extract-status').textContent='No se pudo leer automáticamente. Puedes completar los campos a mano.';throw e;}});
$('#job-results').onclick=e=>{const b=e.target.closest('[data-import-job]');if(!b)return;busy(b,async()=>{const card=JSON.parse(b.dataset.importJob);let job;try{job=await api('/api/jobs/extract','POST',{url:card.url});}catch(err){fillImport(card);$('#import-panel').scrollIntoView({behavior:'smooth'});notice('No se pudo leer el aviso completo ('+err.message+'). Completa la descripción y guarda.',true);return;}const r=await saveJob({...card,...job});notice(r.duplicada?'Esta oportunidad ya estaba guardada.':'Aviso leído, evaluado y guardado.');location.hash='application/'+r.id;})(e);};
bindForm('#import-form',async()=>{const data=formObject($('#import-form'));data.profile_id=state.pid;for(const k of ['anos_obligatorios','meses_relevantes_confirmados','salario_max','salario_min_aceptado'])data[k]=data[k]===''?null:Number(data[k]);data.herramientas=data.herramientas.split(',').map(s=>s.trim()).filter(Boolean);data.vigente=data.vigente===''?null:data.vigente==='true';data.fecha_publicacion=data.fecha_publicacion||null;const r=await api('/api/jobs/import','POST',data);notice(r.duplicada?'Esta oportunidad ya estaba guardada.':'Oportunidad evaluada y guardada.');location.hash='application/'+r.id;});
function card(a){const j=a.vacante||{},analysis=a.detalle?.analisis||{},d=a.detalle?.vacante||{};return `<article class="job-card"><div class="section-heading"><span class="company">${esc(j.empresa)}</span>${badge(a.estado)}</div><h3>${esc(j.titulo)}</h3><p class="job-meta">${esc(d.ubicacion||'Ubicación por comprobar')} · ${esc(d.modalidad||'Modalidad por comprobar')}</p>${d.salario_max?`<p class="job-meta">Salario máximo publicado: S/${esc(d.salario_max)}</p>`:''}<div class="match"><strong>${esc(analysis.compatibilidad??'—')}/100 · Compatibilidad estimada</strong><br>${esc((analysis.requisitos_cumplidos||analysis.componentes?.filter(c=>c.puntos>0).map(c=>c.criterio||c.nombre)||[]).slice(0,2).join(' · ')||'Abre la oferta para revisar requisitos y brechas.')}</div><a class="button secondary" href="#application/${a.id}">Revisar oportunidad</a>${eligible(a)?`<label class="check select-app"><input type="checkbox" data-select-app="${a.id}">Seleccionar para postular en ${autoPortals[portalOf(j.url)]}</label>`:''}</article>`;}
const eligible=a=>!!portalOf(a.vacante?.url)&&['descubierta','preparada','bloqueada'].includes(a.estado)&&!a.detalle?.analisis?.requisito_excluyente;
function batchBar(){const n=$$('[data-select-app]:checked').length;$('#batch-bar').hidden=!n;$('#batch-count').textContent=`${n} candidatura(s) seleccionada(s)`;}
function renderApplications(){const filter=$('#application-filter').value;const list=state.apps.filter(a=>filter==='all'||a.estado===filter||(filter==='blocked'&&['incompatible','bloqueada','pendiente_revision_duplicado','intento_no_confirmado'].includes(a.estado)));$('#applications-list').innerHTML=list.map(card).join('')||empty('Tu búsqueda comienza con una oportunidad','Guarda una vacante para preparar tu CV y seguir sus avances.','#jobs','Explorar oportunidades');batchBar();}
$('#applications-list').addEventListener('change',e=>{if(e.target.matches('[data-select-app]'))batchBar();});
$('#batch-apply').onclick=busy($('#batch-apply'),async()=>{const ids=$$('[data-select-app]:checked').map(x=>Number(x.dataset.selectApp));const chosen=state.apps.filter(a=>ids.includes(a.id));if(!await confirmDialog(`Postular a ${ids.length} vacante(s)`,`<ul>${chosen.map(a=>`<li><strong>${esc(a.vacante.titulo)}</strong> · ${esc(a.vacante.empresa)} · ${autoPortals[portalOf(a.vacante.url)]} · ${esc(a.detalle?.analisis?.compatibilidad??'—')}/100</li>`).join('')}</ul>${sentData()}<p class="muted-note">Se postulan de una en una, con pausas entre cada envío.</p>`,'Autorizar postulaciones'))return;const r=await api(`/api/portals/${state.pid}/apply-batch`,'POST',{application_ids:ids});const ok=r.results.filter(x=>x.queued).length,errors=r.results.filter(x=>!x.queued);await refresh();renderApplications();notice(`${ok} en cola.${errors.length?' No se pudieron poner en cola: '+errors.map(x=>{const a=state.apps.find(y=>y.id===x.application_id);return (a?.vacante?.titulo||x.application_id)+' ('+x.error+')';}).join(' · '):''}`,!ok);});
$('#application-filter').onchange=renderApplications;$('#back-applications').onclick=()=>location.hash='applications';
$('#detail-nav').onclick=busy(null,async e=>{const b=e.target.closest('[data-detail]');if(b){state.detail=b.dataset.detail;await detail();}});
async function detail(){const a=state.apps.find(a=>a.id===state.active);if(!a){$('#detail-content').innerHTML=empty('No encontramos esta candidatura','Vuelve al listado del perfil activo.','#applications','Ver postulaciones');$('#application-heading').innerHTML='';return;}const job=a.vacante||{},analysis=a.detalle?.analisis||{};$('#application-heading').innerHTML=`<div class="page-heading"><div><p class="eyebrow">${esc(job.empresa)}</p><h1>${esc(job.titulo)}</h1>${badge(a.estado)}</div>${href(job.url)?`<a class="button secondary" target="_blank" rel="noopener noreferrer" href="${href(job.url)}">Abrir oferta original ↗</a>`:''}</div>`;$$('[data-detail]').forEach(b=>{b.classList.toggle('active',b.dataset.detail===state.detail);b.setAttribute('aria-pressed',b.dataset.detail===state.detail);});const out=$('#detail-content');
if(state.detail==='vacancy'){out.innerHTML=`<article class="panel auto-panel" id="auto-apply"><h2>Postulación</h2><p>Cargando…</p></article><article class="panel"><h2>Por qué podría encajar contigo</h2><p>Compatibilidad estimada: ${esc(analysis.compatibilidad??'—')}/100. No representa una probabilidad de contratación.</p><h3>Coincidencias</h3><ul>${(analysis.requisitos_cumplidos||analysis.componentes?.filter(c=>c.puntos>0).map(c=>c.criterio||c.nombre)||[]).map(s=>`<li>${esc(s)}</li>`).join('')||'<li>Faltan datos del anuncio para confirmar coincidencias.</li>'}</ul><h3>Por revisar</h3><ul>${[...(analysis.motivos_exclusion||[]),...(analysis.brechas||[]),...(analysis.datos_pendientes||[])].map(s=>`<li>${esc(s)}</li>`).join('')||'<li>Comprueba vigencia y condiciones en el portal.</li>'}</ul>${state.goals.restrictions?`<p>Tus restricciones: ${esc(state.goals.restrictions)}. Revisión manual requerida.</p>`:''}<button class="button primary" data-action="open-cv">Preparar mi CV</button></article><article class="panel"><h2>Descripción de la vacante</h2><p class="description">${esc(a.detalle?.vacante?.descripcion||'Abre el anuncio original para revisar los requisitos completos.')}</p></article>`;await autoPanel(a);}
if(state.detail==='cv'){state.versions=await api(`/api/career/applications/${a.id}/cvs`);out.innerHTML=`<article class="panel"><div class="section-heading"><h2>Un CV para ${esc(job.empresa)}</h2><button class="button primary" data-action="adapt">Crear adaptación</button></div><p>Prioriza funciones y herramientas confirmadas según este anuncio. Cada versión conserva el perfil original y sus cambios.</p><div id="versions">${state.versions.map(versionView).join('')||empty('Tu primera adaptación','Confirma tu perfil y objetivos, y crea una versión para esta candidatura.')}</div></article>`;}
if(state.detail==='answers'){out.innerHTML=`<article class="panel"><h2>Prepara tus respuestas</h2><p>Pega las preguntas reales. Las respuestas quedan vinculadas a esta candidatura.</p><label>Una pregunta por línea<textarea id="questions" rows="5" placeholder="¿Cuál es tu disponibilidad?&#10;¿Qué herramientas manejas?"></textarea></label><button class="button primary" data-action="prepare">Preparar respuestas</button><div id="answer-draft"></div></article>`;const old=[...(a.auditoria||[])].reverse().find(e=>['preparada','bloqueada'].includes(e.accion)&&e.datos?.form_id);if(old){const f=await api('/api/form/'+old.datos.form_id);answerView(f.form_id,f.respuestas,f.aprobado);}}
if(state.detail==='recruiter'){const r=await api(`/api/career/applications/${a.id}/recruiters`);out.innerHTML=`<article class="panel"><h2>Conoce al equipo de selección</h2><p>Búsqueda asistida de perfiles profesionales públicos. Comprueba quién gestiona esta vacante antes de contactarlo.</p><a class="button secondary" href="${href(r.search_url)}" target="_blank" rel="noopener noreferrer">Buscar reclutadores de ${esc(job.empresa)} ↗</a><div>${r.contacts.map(c=>`<div class="diff-row"><h3>${esc(c.name)}</h3><p>${esc(c.role)} · ${esc(c.relationship.replaceAll('_',' '))}</p><p>Formación: ${esc(c.education||'Sin registrar')}<br>Experiencia: ${esc(c.experience||'Sin registrar')}</p><a href="${href(c.source_url)}" target="_blank" rel="noopener noreferrer">Fuente profesional ↗</a><p>Registrado: ${esc(dateLabel(c.checked_at))}. ${esc(c.verification)}</p></div>`).join('')}</div><details><summary>Guardar un contacto profesional</summary><form id="contact-form"><div class="form-grid">${input('Nombre','name')}${input('Cargo actual','role')}${area('Universidad o formación pública','education')}${area('Experiencia profesional pública','experience')}${input('Enlace a la fuente pública','source_url','','url')}</div><label>Relación con la vacante<select name="relationship"><option value="posible_contacto">Posible contacto; sin confirmar</option><option value="responsable_identificado">Responsable identificado</option></select></label>${area('Evidencia de que gestiona esta vacante','evidence')}<button class="button primary">Guardar contacto</button></form></details></article>`;bindForm('#contact-form',async()=>{await api(`/api/career/applications/${a.id}/recruiters`,'POST',formObject($('#contact-form')));await detail();notice('Contacto guardado con su fuente.');});}
if(state.detail==='history'){const vs=await api(`/api/career/applications/${a.id}/cvs`);out.innerHTML=`<article class="panel"><h2>Registrar un avance</h2><p>Marca una postulación como enviada solo si el portal o un correo lo confirma.</p><form id="status-form"><label>Estado<select name="estado">${Object.entries(statuses).filter(([k])=>!['incompatible','bloqueada','pendiente_revision_duplicado'].includes(k)).map(([k,v])=>`<option value="${k}" ${a.estado===k?'selected':''}>${v}</option>`).join('')}${a.estado==='pendiente_revision_duplicado'?'<option value="duplicado_descartado">Confirmé que son vacantes diferentes</option>':''}</select></label><label>Tipo de evidencia<select name="tipo_evidencia"><option value="">Selecciona si hubo envío</option><option value="mensaje_portal">Mensaje del portal</option><option value="correo_confirmacion">Correo de confirmación</option><option value="id_candidatura">Identificador de candidatura</option></select></label>${area('Evidencia','evidencia')}<label>CV utilizado<select name="cv_version_id"><option value="">Sin versión asociada</option>${vs.filter(v=>v.approved).map(v=>`<option value="${v.id}">Versión ${v.id} · ${esc(dateLabel(v.created))}</option>`).join('')}</select></label>${area('Nota o aclaración','nota')}<button class="button primary">Guardar avance</button></form></article><article class="panel"><h2>Historial de la candidatura</h2><div class="timeline">${[...(a.auditoria||[])].reverse().map(e=>`<div class="timeline-item"><strong>${esc(actionLabels[e.accion]||e.accion.replaceAll('_',' '))}</strong><p>${esc(dateLabel(e.fecha))}</p>${e.datos?.evidencia?`<p>${esc(e.datos.evidencia)}</p>`:''}${e.datos?.mensaje?`<p>${esc(e.datos.mensaje)}</p>`:''}${e.datos?.captura&&e.datos?.run_id?`<p><a target="_blank" rel="noopener" href="/api/portals/runs/${Number(e.datos.run_id)}/captura">Ver captura del portal ↗</a></p>`:''}${e.datos?.version_id?`<p>CV versión ${e.datos.version_id}</p>`:''}</div>`).join('')}</div></article>`;bindForm('#status-form',async()=>{const d=formObject($('#status-form'));d.cv_version_id=d.cv_version_id?Number(d.cv_version_id):null;await api(`/api/applications/${a.id}`,'PATCH',d);await refresh();await detail();notice('Avance registrado con trazabilidad.');});}}
function versionView(v){return `<details ${v===state.versions[0]?'open':''}><summary>Versión ${v.id} · ${esc(dateLabel(v.created))} · ${v.approved?'Aprobada':'Por revisar'}</summary><div class="actions"><a class="button secondary" href="/api/career/cv/${v.id}/download?format=docx">Descargar DOCX</a><a class="button secondary" href="/api/career/cv/${v.id}/download?format=latex">Fuente LaTeX</a>${!v.approved?`<button class="button primary" data-action="approve-cv" data-id="${v.id}">Aprobar esta versión</button>`:''}</div>${v.changes.map(c=>`<div class="diff-row"><h3>${esc(c.campo)}</h3><p>${esc(c.motivo)}</p><details><summary>Ver qué cambió</summary><p>Antes: ${esc(c.antes)}</p><p class="after">Ahora: ${esc(c.despues)}</p></details></div>`).join('')||'<p>Se conserva el contenido: no se identificaron cambios de orden relevantes.</p>'}<label class="cv-side-selector">Vista<select data-cv-side><option value="adapted">CV adaptado</option><option value="original">CV original</option></select></label><div class="cv-comparison"><div class="cv-original"><h3>Original</h3><iframe sandbox title="CV original" srcdoc="${esc(v.original_html)}"></iframe></div><div class="cv-adapted"><h3>Adaptado</h3><iframe sandbox title="CV adaptado" srcdoc="${esc(v.cv_html)}"></iframe></div></div></details>`;}
function answerView(id,answers,approved=false){$('#answer-draft').innerHTML=`<form id="answers-review" data-id="${id}">${answers.map((a,i)=>`<label>${esc(a.label)}${a.bloqueada?' · Requiere intervención personal':''}<textarea rows="3" data-field="${esc(a.field_id)}" ${a.bloqueada?'disabled':''}>${esc(a.answer)}</textarea>${a.opciones?.length?`<small>Opciones del portal: ${esc(a.opciones.join(' · '))}. Escribe exactamente una.</small><br>`:''}<small>${esc(a.nota||a.fuente||'Dato pendiente de confirmar')}</small></label>`).join('')}<button class="button primary" ${answers.some(a=>a.bloqueada)?'disabled':''}>${approved?'Guardar nueva revisión':'Aprobar respuestas revisadas'}</button><p>Las respuestas aprobadas se usan en la postulación automática de esta vacante, o puedes copiarlas al portal.</p></form>`;bindForm('#answers-review',async()=>{const edits=$$('#answers-review textarea').map(t=>({field_id:t.dataset.field,answer:t.value}));await api(`/api/form/${id}/approve`,'POST',{edits});await refresh();notice('Respuestas aprobadas. Vuelve a “Vacante” para reintentar la postulación automática.');});}
async function autoPanel(a){const box=$('#auto-apply');if(!box)return;const [r,s]=await Promise.all([api(`/api/portals/applications/${a.id}/runs`),api(`/api/portals/${state.pid}`)]);if(state.active!==a.id||state.detail!=='vacancy'||!$('#auto-apply'))return;
if(!r.supported){box.innerHTML=`<h2>Postulación</h2><p>${esc(r.note||'La postulación automática funciona con avisos de Bumeran y Computrabajo. Postula desde el aviso original y registra la evidencia en Historial.')}</p><button class="button secondary" data-detail-go="answers">Preparar respuestas para copiar</button>`;return;}
const name=autoPortals[r.portal],acct=s.accounts.find(x=>x.portal===r.portal),last=r.runs[0],active=last&&['en_cola','ejecutando'].includes(last.status),done=a.estado==='postulada';
const completing=done&&last?.status==='postulada'&&last.questions?.length&&!active;
const reasons=[];if(done&&!completing)reasons.push('Esta candidatura ya tiene una postulación confirmada.');if(!s.browser_available)reasons.push(s.browser_note);if(acct?.status!=='connected')reasons.push(`Conecta tu cuenta de ${name} en Conexiones.`);if(['incompatible','pendiente_revision_duplicado','vencida','rechazada'].includes(a.estado))reasons.push('Revisa la vacante: está marcada como incompatible, duplicada o cerrada.');
const uncertain=last?.status==='intento_no_confirmado'&&!done;
box.innerHTML=`<div class="section-heading"><h2>Postulación automática en ${esc(name)}</h2>${last?`<span class="badge ${last.status==='postulada'?'success':['bloqueada','intento_no_confirmado'].includes(last.status)?'warning':last.status==='error'?'error':''}">${esc(runLabels[last.status]||last.status)}</span>`:''}</div>
${last?`<p>${esc(last.status==='postulada'?'Evidencia: '+last.evidence:last.message||'')}</p>${last.status==='postulada'&&last.message?`<p>${esc(last.message)}</p>`:''}${last.questions?.length?`<ul class="run-list">${last.questions.map(q=>`<li><strong>${esc(q.label)}</strong> — ${esc(q.reason)}</li>`).join('')}</ul><button class="button secondary" data-detail-go="answers">Responder estas preguntas</button>`:''}${last.filled?.length?`<details><summary>Datos que JobFlow completó (${last.filled.length})</summary><ul class="run-list">${last.filled.map(f=>`<li>${esc(f.label)}: ${esc(f.value)} <small>(${esc(f.source)})</small></li>`).join('')}</ul></details>`:''}${last.screenshot?`<p><a target="_blank" rel="noopener" href="${esc(last.screenshot)}">Ver captura del portal ↗</a></p>`:''}`:`<p>JobFlow abre el aviso con tu sesión de ${esc(name)}, completa datos confirmados y envía solo si todo está verificado.</p>`}
${reasons.length?`<p class="muted-note">${reasons.map(esc).join(' ')}</p>`:''}
${completing?`<div class="actions"><button class="button primary" data-auto-apply="complete" ${reasons.length?'disabled':''}>Enviar respuestas al portal</button></div><p class="muted-note">Primero responde y aprueba las preguntas en «Respuestas». JobFlow no vuelve a postular: solo completa las preguntas.</p>`:''}
${done||active?'':`<div class="actions"><button class="button primary" data-auto-apply="${uncertain?'retry':'go'}" ${reasons.length?'disabled':''}>${uncertain?'Revisé el portal: no se envió, reintentar':last?.status==='bloqueada'?'Reintentar postulación':'Postular automáticamente'}</button>${acct?.status!=='connected'?'<a class="button secondary" href="#connections">Conectar cuenta</a>':''}</div>`}`;
clearTimeout(state.autoTimer);if(active)state.autoTimer=setTimeout(async()=>{if(state.active===a.id&&state.detail==='vacancy'&&location.hash==='#application/'+a.id){await refresh();const fresh=state.apps.find(x=>x.id===a.id);if(fresh&&fresh.estado!==a.estado)await detail();else await autoPanel(fresh||a);}},5000);}
$('#detail-content').addEventListener('click',e=>{const go=e.target.closest('[data-detail-go]');if(go){state.detail=go.dataset.detailGo;detail().catch(err=>notice(err.message,true));return;}const b=e.target.closest('[data-auto-apply]');if(!b)return;busy(b,async()=>{const a=state.apps.find(x=>x.id===state.active),retry=b.dataset.autoApply==='retry',complete=b.dataset.autoApply==='complete';if(!await confirmDialog(complete?'Enviar respuestas al portal':retry?'Reintentar la postulación':'Autorizar postulación automática',`<p><strong>${esc(a.vacante.titulo)}</strong> · ${esc(a.vacante.empresa)} · ${autoPortals[portalOf(a.vacante.url)]}<br>Compatibilidad estimada: ${esc(a.detalle?.analisis?.compatibilidad??'—')}/100</p>${retry?'<p><strong>Confirma que revisaste tus postulaciones en el portal y esta no figura.</strong> Si figura, registra la evidencia en Historial en lugar de reintentar.</p>':''}${complete?'<p>JobFlow abrirá tu postulación y enviará las respuestas que aprobaste. No se crea una postulación nueva.</p>':''}${sentData()}`,complete?'Enviar respuestas':retry?'No figura: reintentar':'Autorizar postulación'))return;await api(`/api/portals/applications/${a.id}/apply`,'POST',{confirm_not_sent:retry,complete_questions:complete});notice('Postulación en cola. Verás el resultado aquí.');await refresh();await detail();})(e);});
$('#detail-content').addEventListener('change',e=>{if(e.target.matches('[data-cv-side]'))e.target.closest('details').querySelector('.cv-comparison').classList.toggle('show-original',e.target.value==='original');});
$('#detail-content').addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;await busy(b,async()=>{switch(b.dataset.action){case 'open-cv':state.detail='cv';await detail();break;case 'adapt':await api(`/api/career/applications/${state.active}/cv`,'POST');await refresh();await detail();notice('CV adaptado. Revisa los cambios antes de aprobar.');break;case 'approve-cv':await api(`/api/career/cv/${b.dataset.id}/approve`,'POST');await detail();notice('Versión aprobada y conservada.');break;case 'prepare':const schema=lines($('#questions').value).map((label,i)=>({id:'q'+i,label,type:'text'}));if(!schema.length)throw Error('Pega al menos una pregunta del portal.');const f=await api(`/api/applications/${state.active}/prepare`,'POST',{profile_id:state.pid,form_schema:schema});answerView(f.form_id,f.answers);await refresh();break;}})(e);});
function renderAgenda(){const f=$('#event-form');$('#event-application').innerHTML='<option value="">Sin asociar</option>'+state.apps.map(a=>`<option value="${a.id}">${esc(a.vacante?.empresa)} · ${esc(a.vacante?.titulo)}</option>`).join('');$('#events-list').innerHTML=state.events.map(e=>`<article class="panel"><span class="badge ${e.confirmed?'success':'warning'}">${e.confirmed?'Confirmado':'Por confirmar'}</span><h3>${esc(e.title)}</h3><p>${esc(dateLabel(e.start))}<br>${esc(e.location)}</p><p>${e.sync_status==='synced'?'Sincronizado con Google Calendar':'Guardado en JobFlow'}</p><div class="actions"><a class="button secondary" href="/api/career/events/${e.id}/ics">Descargar evento</a><button class="button secondary" data-edit-event="${e.id}">Editar</button>${e.confirmed?`<button class="button secondary" data-sync-event="${e.id}">Sincronizar Google</button>`:''}</div></article>`).join('')||empty('Una agenda para llegar preparado','Añade tu próxima entrevista o un recordatorio de seguimiento.');}
function localTime(value,tz){return new Intl.DateTimeFormat('sv-SE',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value)).replace(' ','T');}
$('#events-list').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editEvent){const ev=state.events.find(x=>x.id===b.dataset.editEvent),f=$('#event-form');for(const k of ['id','title','application_id','timezone','kind','source','location'])f.elements[k].value=ev[k]??'';for(const k of ['start','end'])f.elements[k].value=localTime(ev[k],ev.timezone);f.elements.confirmed.checked=ev.confirmed;$('#event-form-title').textContent='Editar evento';f.scrollIntoView({behavior:'smooth'});}else if(b.dataset.syncEvent)await busy(b,async()=>{await api('/api/google/events/'+b.dataset.syncEvent+'/sync','POST');await refresh();renderAgenda();notice('Evento sincronizado. No se enviaron invitaciones.');})(e);};
$('#cancel-event').onclick=()=>{$('#event-form').reset();$('#event-form-title').textContent='Añadir un evento';};
bindForm('#event-form',async()=>{const f=$('#event-form'),d=formObject(f),id=d.id;delete d.id;d.profile_id=state.pid;d.application_id=d.application_id?Number(d.application_id):null;d.confirmed=f.elements.confirmed.checked;for(const k of ['start','end'])d[k]+=(d.timezone==='UTC'?'+00:00':'-05:00');await api('/api/career/events'+(id?'/'+id:''),id?'PUT':'POST',d);f.reset();await refresh();renderAgenda();notice('Evento guardado. Puedes descargarlo o sincronizarlo con Google.');});
async function portalsView(){const s=await api('/api/portals/'+state.pid);state.portalAccounts=s.accounts;$('#portal-note').hidden=s.browser_available;$('#portal-note').textContent=s.browser_note;$('#portal-queue').textContent=s.queue?`${s.queue} en cola`:`Hasta ${s.daily_limit} postulaciones por día`;
$('#portal-accounts').innerHTML=s.accounts.map(a=>{const on=a.status==='connected',login=a.login;return `<article class="panel"><span class="badge ${on?'success':a.status==='expired'?'warning':''}">${on?'Conectada':a.status==='expired'?'Sesión vencida':'Sin conectar'}</span><h2>${esc(a.nombre)}</h2><p>${on?`Conectada el ${esc(dateLabel(a.connected_at))}. Puedes postular automáticamente a sus avisos.`:'Inicia sesión una vez para autorizar postulaciones en este portal.'}</p>${a.riesgo?`<p class="muted-note">⚠ ${esc(a.riesgo)} Máximo ${esc(a.limite_diario)} postulaciones por día.</p>`:''}${login&&login.status!=='conectada'?`<p class="connection-account">${esc(login.message)}</p>`:''}<div class="actions">${login&&['abriendo','esperando','verificando'].includes(login.status)?`<button class="button primary" data-portal-verify="${a.portal}" ${login.status==='esperando'?'':'disabled'}>${login.status==='verificando'?'Comprobando…':'Ya inicié sesión'}</button><button class="button secondary" data-portal-cancel="${a.portal}">Cancelar</button>`:on?`<button class="button secondary" data-portal-connect="${a.portal}" ${s.browser_available?'':'disabled'}>Renovar sesión</button><button class="button secondary" data-portal-disconnect="${a.portal}">Desconectar</button>`:`<button class="button primary" data-portal-connect="${a.portal}" ${s.browser_available?'':'disabled'}>Conectar ${esc(a.nombre)}</button>`}</div></article>`;}).join('');const own=href(state.profile?.linkedin||'');$('#portal-prepared').innerHTML=(s.prepared||[]).map(x=>`<article class="panel"><span class="badge">Solo preparación</span><h2>${esc(x.nombre)}</h2><p>${esc(x.nota)}</p>${x.portal==='linkedin'?(own?`<p class="connection-account">Tu perfil: <a href="${own}" target="_blank" rel="noopener noreferrer">${esc(state.profile.linkedin)}</a></p>`:'<p class="connection-account">Añade el enlace de tu perfil en el campo «LinkedIn» de tus datos para usarlo en tus postulaciones.</p>'):''}${x.url?`<a class="button secondary" href="${href(x.url)}" target="_blank" rel="noopener noreferrer">Abrir ${esc(x.nombre)}</a>`:'<a class="button secondary" href="#jobs">Pegar un aviso</a>'}</article>`).join('');
const wasLogging=state.loggingIn||[];state.loggingIn=s.accounts.filter(a=>a.login&&['abriendo','esperando','verificando'].includes(a.login.status)).map(a=>a.portal);
for(const a of s.accounts)if(wasLogging.includes(a.portal)&&!state.loggingIn.includes(a.portal)&&a.login)notice(a.login.message,a.login.status!=='conectada');
clearTimeout(state.portalTimer);if(state.loggingIn.length)state.portalTimer=setTimeout(()=>{if(['#profile','#portals'].includes(location.hash))portalsView().catch(()=>{});},2500);}
$('#portal-accounts').onclick=e=>{const b=e.target.closest('[data-portal-connect],[data-portal-disconnect],[data-portal-verify],[data-portal-cancel]');if(!b)return;busy(b,async()=>{const d=b.dataset,base=`/api/portals/${state.pid}/`;if(d.portalConnect){const acct=(state.portalAccounts||[]).find(x=>x.portal===d.portalConnect);let body;if(acct?.riesgo){if(!await confirmDialog(`Conectar ${acct.nombre}`,`<p>${esc(acct.riesgo)}</p><p class="muted-note">JobFlow postulará como máximo ${esc(acct.limite_diario)} veces por día en ${esc(acct.nombre)}, con pausas, y solo en avisos con postulación dentro del portal.</p>`,'Acepto el riesgo y quiero conectar'))return;body={acepto_riesgo:true};}const r=await api(base+d.portalConnect+'/connect','POST',body);notice(r.message);}else if(d.portalVerify){await api(base+d.portalVerify+'/verify','POST');}else if(d.portalCancel){await api(base+d.portalCancel+'/cancel','POST');}else{const r=await api(base+d.portalDisconnect+'/disconnect','POST');notice(r.note);}await portalsView();})(e);};
async function connections(){const status=await api(`/api/google/${state.pid}/status`),labels={gmail_read:['Gmail · Selección','Lee correos recientes relacionados con procesos laborales.'],gmail_send:['Gmail · Resumen diario','Envía tus avances a tu propia cuenta conectada.'],calendar:['Google Calendar','Añade o actualiza eventos confirmados en tu calendario.']};$('#google-connections').innerHTML=Object.entries(status.services).map(([service,s])=>`<article class="panel"><span class="badge ${s.connected?'success':'warning'}">${s.connected?'Conectado':s.configured?'Sin conectar':'Configuración pendiente'}</span><h2>${labels[service][0]}</h2><p>${labels[service][1]}</p>${s.email?`<p class="connection-account">${esc(s.email)}</p>`:''}<button class="button secondary" data-service="${service}" data-connected="${s.connected}" ${!s.connected&&!s.configured?'disabled':''}>${s.connected?'Desconectar':'Conectar con Google'}</button>${!s.configured?'<p>El administrador debe configurar las credenciales Google de JobFlow.</p>':''}</article>`).join('');if(status.last_sync)$('#google-connections').insertAdjacentHTML('beforeend',`<p>Última revisión: ${esc(dateLabel(status.last_sync))}</p>`);if(status.scheduler_error)notice(status.scheduler_error,true);const f=$('#settings-form');for(const [k,v] of Object.entries(state.setup.settings))if(f.elements[k]){if(f.elements[k].type==='checkbox')f.elements[k].checked=v;else f.elements[k].value=v;}$('#scheduler-note').textContent=status.scheduler_configured?'El servicio está configurado para revisar tareas cada minuto mientras el servidor permanezca activo.':'La programación requiere activar el servicio de tareas. Mientras tanto puedes sincronizar y enviar el resumen manualmente.';$('#send-digest').disabled=!status.services.gmail_send.connected;$('#sync-gmail').disabled=!status.services.gmail_read.connected;const mail=await api(`/api/google/${state.pid}/mail`);$('#mail-list').innerHTML=mail.map(m=>`<details><summary>${esc(m.subject)}</summary><p>${esc(m.from)}</p><p class="description">${esc(m.body)}</p><a class="button secondary" href="#agenda">Revisar fecha y añadir a agenda</a></details>`).join('')||empty('Tu seguimiento, en un lugar','Conecta Gmail para importar correos. También puedes pegar uno abajo.');const manual=await api('/api/emails');$('#manual-mails').innerHTML=(Array.isArray(manual)?manual:[]).slice(0,15).map(m=>`<details><summary>${esc(m.asunto)}</summary><p>${esc(m.remitente)}</p><p class="description">${esc(m.cuerpo||'')}</p></details>`).join('');}
$('#google-connections').onclick=async e=>{const b=e.target.closest('[data-service]');if(!b)return;await busy(b,async()=>{if(b.dataset.connected==='true'){await api(`/api/google/${state.pid}/${b.dataset.service}/disconnect`,'POST');await refresh();await connections();notice('Conexión desactivada para este perfil.');}else{const r=await api(`/api/google/${state.pid}/${b.dataset.service}/connect`,'POST');location.assign(r.url);}})(e);};
bindForm('#settings-form',async()=>{const f=$('#settings-form'),d=formObject(f);for(const k of ['digest_enabled','gmail_sync_enabled','calendar_auto'])d[k]=f.elements[k].checked;await api(cpath('settings'),'PUT',d);theme(d.theme);await refresh();notice('Preferencias guardadas.');});
$('#send-digest').onclick=busy($('#send-digest'),async()=>{const r=await api(`/api/google/${state.pid}/digest/send`,'POST');notice(r.duplicate?'El resumen de hoy ya tiene un intento registrado: '+r.status:'Resumen enviado a '+r.recipient);});
$('#sync-gmail').onclick=busy($('#sync-gmail'),async()=>{const r=await api(`/api/google/${state.pid}/gmail/sync`,'POST');await connections();notice(`${r.imported} correos importados.${r.more_available?' Hay más resultados; revisa Gmail para completar la revisión.':''}`);});
bindForm('#email-form',async()=>{await api('/api/emails/import','POST',formObject($('#email-form')));await connections();notice('Correo clasificado y guardado. Revisa sus datos antes de actuar.');});
function renderProfiles(){const list=state.profiles,max=state.user?.max_profiles||3,full=list.length>=max,has=Boolean(state.pid);$('#profiles-panel').hidden=!list.length;$('#profiles-count').textContent=`${list.length} de ${max}`;$('#profiles-count').className='badge'+(list.length>max?' error':full?' warning':'');$('#profiles-note').textContent=list.length>max?`Tienes más perfiles que el máximo permitido (${max}). Puedes seguir usándolos, pero para crear otro primero debes borrar ${list.length-max+1}.`:full?`Llegaste al máximo de ${max} perfiles. Para crear otro, borra alguno. Para cambiar de CV no necesitas uno nuevo: actualiza el perfil activo.`:`Puedes tener hasta ${max} perfiles. Para cambiar de CV no necesitas uno nuevo: actualiza el perfil activo.`;
$('#profiles-list').innerHTML=list.map(p=>`<div class="profile-row"><label class="check"><input type="checkbox" value="${p.id}"><span><strong>${esc(p.nombre||'Perfil sin nombre')}</strong>${p.id===state.pid?'<span class="badge">Activo</span>':''}<br><small>${esc(p.fuente_cv)}${p.fecha?' · '+esc(dateLabel(p.fecha)):''} · ${p.postulaciones} postulación(es)</small></span></label><button type="button" class="text-button danger-text" data-delete-profile="${p.id}">Eliminar</button></div>`).join('');$('#delete-profiles').hidden=list.length<2;
$('#upload-main').textContent=has?'Actualizar este perfil':'Extraer datos del CV';$('#upload-new').hidden=!has;$('#upload-new').disabled=full;$('#upload-limit').hidden=!(has&&full);$('#upload-limit').textContent=`Ya tienes ${list.length} de ${max} perfiles: borra alguno para crear uno nuevo.`;if(!has){$('#upload-title').textContent='Comienza con tu CV';$('#upload-text').textContent=`PDF, DOCX o TXT · hasta 10 MB. Puedes tener hasta ${max} perfiles.`;}}
async function deleteProfiles(ids){const chosen=state.profiles.filter(p=>ids.includes(p.id));if(!chosen.length)return;const apps=chosen.reduce((n,p)=>n+p.postulaciones,0);if(!await confirmDialog(chosen.length>1?`¿Eliminar ${chosen.length} perfiles?`:'¿Eliminar este perfil?',`<ul>${chosen.map(p=>`<li><strong>${esc(p.nombre||'Perfil sin nombre')}</strong> · ${esc(p.fuente_cv)}</li>`).join('')}</ul><p>Se borrarán para siempre sus datos y ${apps} postulación(es) con su historial, CV adaptados, respuestas, agenda, capturas y conexiones de portales y Google.</p><p class="muted-note">No se puede deshacer. Si solo quieres cambiar de CV, usa «Actualizar este perfil».</p>`,'Eliminar para siempre',true))return;let done=0;try{for(const p of chosen){await api(`/api/profiles/${p.id}`,'DELETE');done++;}}finally{if(done){$('#job-results').innerHTML='';$('#event-form').reset();await profiles();await route();}}notice(`${done} perfil(es) eliminado(s).`);}
$('#profiles-list').onclick=e=>{const b=e.target.closest('[data-delete-profile]');if(b)busy(b,()=>deleteProfiles([Number(b.dataset.deleteProfile)]))(e);};
$('#delete-profiles').onclick=busy($('#delete-profiles'),async()=>{const ids=$$('#profiles-list input:checked').map(i=>Number(i.value));if(!ids.length)throw Error('Marca los perfiles que quieres eliminar.');await deleteProfiles(ids);});
async function claimPanel(){const list=await api('/api/account/unclaimed');$('#claim-panel').hidden=!list.length;$('#claim-list').innerHTML=list.map(p=>`<label class="check"><input type="checkbox" value="${p.id}"><span><strong>${esc(p.nombre||'Perfil sin nombre')}</strong><br><small>${esc(p.fuente_cv)}${p.fecha?' · '+esc(dateLabel(p.fecha)):''}</small></span></label>`).join('');}
bindForm('#claim-form',async()=>{const ids=$$('#claim-list input:checked').map(i=>Number(i.value));if(!ids.length)throw Error('Marca los perfiles que son tuyos.');const r=await api('/api/account/claim','POST',{profile_ids:ids});if(!state.pid)state.pid=ids[0];await profiles();await route();notice(`${r.claimed} perfil(es) pasaron a tu cuenta. Solo tú puedes verlos ahora.`);});
function showAuth(mode){state.user=null;document.body.classList.add('signed-out');$('#account-menu').hidden=true;$('#auth-screen').hidden=false;authMode(mode);}
function authMode(mode){const f=$('#auth-form'),reg=mode==='register';f.dataset.mode=mode;$$('[data-auth-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.authMode===mode);b.setAttribute('aria-selected',String(b.dataset.authMode===mode));});$$('#auth-form .register-only').forEach(el=>{el.hidden=!reg;const i=el.querySelector('input');i.disabled=!reg;i.required=reg&&i.name==='password2';});f.elements.password.autocomplete=reg?'new-password':'current-password';$('#auth-title').textContent=reg?'Crea tu cuenta':'Hola de nuevo';$('#auth-subtitle').textContent=reg?'Tus perfiles y postulaciones quedarán separados de las demás cuentas.':'Entra a tu espacio de búsqueda.';$('#auth-submit').textContent=reg?'Crear cuenta':'Iniciar sesión';$('#auth-error').hidden=true;}
$$('[data-auth-mode]').forEach(b=>b.onclick=()=>authMode(b.dataset.authMode));
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const f=$('#auth-form'),reg=f.dataset.mode==='register',d=formObject(f),err=$('#auth-error'),btn=$('#auth-submit');err.hidden=true;if(reg&&d.password!==d.password2){err.textContent='Las contraseñas no coinciden.';err.hidden=false;return;}delete d.password2;btn.disabled=true;try{await api('/api/auth/'+(reg?'register':'login'),'POST',d);location.reload();}catch(x){err.textContent=x.message;err.hidden=false;btn.disabled=false;}});
function accountMenu(open){$('#account-menu').hidden=!open;$('#avatar').setAttribute('aria-expanded',String(open));}
$('#avatar').onclick=e=>{e.stopPropagation();accountMenu($('#account-menu').hidden);};document.addEventListener('click',e=>{if(!e.target.closest('.account'))accountMenu(false);});document.addEventListener('keydown',e=>{if(e.key==='Escape')accountMenu(false);});$$('#account-menu a').forEach(a=>a.addEventListener('click',()=>accountMenu(false)));
$('#logout').onclick=busy($('#logout'),async()=>{await api('/api/auth/logout','POST');location.replace(location.pathname);});
$('#profile-picker').onchange=busy(null,async()=>{state.pid=Number($('#profile-picker').value);$('#job-results').innerHTML='';$('#event-form').reset();$('#notice').hidden=true;if(location.hash.startsWith('#application/'))location.hash='applications';else await route();});window.addEventListener('hashchange',route);
(async()=>{let me=null;try{const r=await fetch('/api/auth/me');if(r.ok)me=await r.json();}catch{}if(!me){showAuth('login');return;}state.user=me;document.body.classList.remove('signed-out');$('#account-name').textContent=me.nombre;$('#account-username').textContent='@'+me.username;$('#avatar').textContent=(me.nombre||me.username)[0].toUpperCase();try{await profiles();await route();}catch(e){notice(e.message,true);}})();
